### ISSUE TITLE
Install npm dependencies from package.json

### ISSUE THREAD

**Issue by schmidsi** [DispatchMe/mgp#42]
Grüezi,

We had the following error on our buildservers (codeship.com) when testing Meteor packages which depend on other Meteor packages:

```
W20161223-15:19:15.769(1)? (STDERR) /Users/schmidsi/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161223-15:19:15.828(1)? (STDERR) 						throw(ex);
W20161223-15:19:15.828(1)? (STDERR) 						^
W20161223-15:19:15.829(1)? (STDERR) 
W20161223-15:19:15.829(1)? (STDERR) Error: Can't find npm module 'lodash'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20161223-15:19:15.829(1)? (STDERR)     at Object.require (/private/var/folders/mc/skskq1wd615g5fkh7zrlt6nw0000gn/T/meteor-test-run1wmhyxx/.meteor/local/build/programs/server/boot.js:200:17)
W20161223-15:19:15.829(1)? (STDERR)     at options.fallback (packages/modules-runtime.js:445:18)
W20161223-15:19:15.830(1)? (STDERR)     at Module.require (packages/modules-runtime.js:112:16)
W20161223-15:19:15.830(1)? (STDERR)     at Module.Mp.import (/Users/schmidsi/.meteor/packages/modules/.0.7.7.yjn28g++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20161223-15:19:15.830(1)? (STDERR)     at meteorInstall.node_modules.meteor.optune:meteor-model.schemas.subschemas.Booking.js (packages/optune:meteor-model/schemas/subschemas/Booking.js:1:1)
W20161223-15:19:15.830(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161223-15:19:15.831(1)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20161223-15:19:15.832(1)? (STDERR)     at Module.Mp.import (/Users/schmidsi/.meteor/packages/modules/.0.7.7.yjn28g++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20161223-15:19:15.832(1)? (STDERR)     at meteorInstall.node_modules.meteor.optune:meteor-model.common.js (packages/optune:meteor-model/common.js:1:1)
W20161223-15:19:15.833(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
```

After some try & error, I found that this error comes from the depended packages. If the depended packages have declared NPM dependencies inside their `package.json` (the recommended way from Meteor 1.3 upwards) instead of via `Npm.depends` in `package.js`.

The solution would be to go into every Meteor git package and install its NPM dependencies, like with `npm install`.

To make things more clear, I try to sketch out the architecture a bit better:

We have a Meteor package named "Methods" which depends on another Meteor package named "Model". This "Model" has NPM dependencies inside `package.json`. When I install & test "Methods" and install its Meteor dependencies with `mgp`, it does install "Model" but does not install its NPM dependencies.

To fix this, best would be to have `mgp` to also install the NPM dependencies of each Meteor package.

I'd implement this feature by myself, I just wanted to ask if you would merge such a pull request or if you think there is another way to work around this issue. If you let me create a pull request, I'd be happy if you can also point me to the right place in the code base to start.

Thanks for this awesome package so far

**Comment by aldeed** [comment]
Hi @schmidsi, I don't think it's true that Meteor pkgs are supposed to use their own package.json. The [guide](https://guide.meteor.com/writing-atmosphere-packages.html#dependencies) still says to use `Npm.depends`, or you can use any NPM package but expect that the app will have installed it in its own package.json (e.g., using checkNpmVersions).

Currently I typically use the `checkNpmVersions` approach, and add all the dependencies to the app's `package.json`. Then I also add `mgp` as a dev dependency for the app and do this in the app's `package.json`:

```json
  "scripts": {
    "postinstall": "mgp",
  },
```

That way you only need to do `npm i` in the app directory and it will install both NPM and Meteor packages.

Does this approach work? We could accept a PR to run `npm i` for each package after copying, but I'm just not sure that is a pattern people should be following.

**Comment by schmidsi** [comment]
Hi @aldeed, thanks for your reply. It works fine like this when I test the "Webapp". But if I run tests on the package "Methods", which depends on the package "Model", it does not work somehow. Does this make sense for you?

I have found a possible workaround with [recursive-install](https://www.npmjs.com/package/recursive-install). I will post here again if I manage to successfully run my tests again. But there are some other problems ATM which I have to investigate first.
